SELECT * FROM VENDEDOR;

--EN UN UPDATE NO DEBEMOS ACTUALIZAR EL PK, NO TENDRÍA SENTIDO
/* EJEMPLO NO. 1*/
UPDATE VENDEDOR SET NOMBRE_VENDEDOR='NACHA', AREA_VENTAS='CHALCO' WHERE NUMERO_VENDEDOR=3462;

SET SERVEROUTPUT ON;
--UNA ACTUALIZACIÓN CORRECTA
CREATE OR REPLACE PROCEDURE ACTUALIZAR_VENDEDOR(MY_ID IN INTEGER, MY_NOMBRE IN VARCHAR2, MY_AREA IN VARCHAR2)
AS
BEGIN
UPDATE VENDEDOR SET NOMBRE_VENDEDOR=MY_NOMBRE, AREA_VENTAS=MY_AREA WHERE NUMERO_VENDEDOR=MY_ID;
DBMS_OUTPUT.PUT_LINE('REGISTRO ACTUALIZADO');
END;
/

BEGIN
ACTUALIZAR_VENDEDOR(3462,'CLODOMIRO','CHALCATONGO');
END;
/