CREATE TABLE ALMACEN (NUMERO_ALMACEN INTEGER, UBICACION_ALMACEN VARCHAR2(40),
                     CONSTRAINT PK_NA PRIMARY KEY(NUMERO_ALMACEN)
                     );
                     
CREATE TABLE VENDEDOR(NUMERO_VENDEDOR INTEGER, NOMBRE_VENDEDOR VARCHAR2(60),
                      AREA_VENTAS VARCHAR2(40),
                      CONSTRAINT PK_NV PRIMARY KEY(NUMERO_VENDEDOR)
                      );
                        
         
      CREATE TABLE CLIENTE(NUMERO_CLIENTE INTEGER, NUMERO_ALMACEN INTEGER,
      NOMBRE_CLIENTE VARCHAR2(50),
      CONSTRAINT PK_NC PRIMARY KEY(NUMERO_CLIENTE),
      CONSTRAINT FK_NA1 FOREIGN KEY(NUMERO_ALMACEN) REFERENCES ALMACEN(NUMERO_ALMACEN)
      );
      
      CREATE TABLE VENTAS(ID_VENTAS INTEGER, NUMERO_CLIENTE INTEGER, 
      NUMERO_VENDEDOR INTEGER, MONTO_VENTA FLOAT,
      CONSTRAINT PK_IDV PRIMARY KEY(ID_VENTAS),
      CONSTRAINT FK_NC1 FOREIGN KEY(NUMERO_CLIENTE) REFERENCES CLIENTE(NUMERO_CLIENTE),
      CONSTRAINT FK_NV1 FOREIGN KEY(NUMERO_VENDEDOR) REFERENCES VENDEDOR(NUMERO_VENDEDOR)
      );
      
      CREATE SEQUENCE SEC_VENTAS
      START WITH 1
      INCREMENT BY 1
      NOMAXVALUE;
      
      
      
      
      
         
         
         
         
         
         
                      
                      