-- Procedimientos

CREATE OR REPLACE PROCEDURE ACTUALIZAR_ALMACEN (MY_ID IN INTEGER, MI_UBICACION VARCHAR2)
AS BEGIN
UPDATE ALMACEN SET UBICACION_ALMACEN=MI_UBICACION WHERE NUMERO_ALMACEN=MY_ID;
END;
/
SELECT * FROM ALMACEN;

BEGIN
ACTUALIZAR_ALMACEN(1,'CHALO');
END;
/